### ISSUE TITLE
requesting query addition for Eulachon surveys

### ISSUE THREAD

**Issue by vhodes** [pbs-assess/gfdata#1]
Need survey samples and indices

TRIP_ID	TRIP_COMMENT
82851	The very first Eulachon bottom trawl survey!
82870	The exciting second Eulachon survey!
82872	The fantastic third Eulachon survey!
82930	The fantastic fourth Eulachon survey!
82994	The fabulous fifth Eulachon survey.
83010	Sixth sweet Eulachon survey!
83050	Seventh swell Eulachon survey!
83090	Eighth Enlightening Eulachon Extravaganza!
83411	Ninth nifty Eulachon survey!
83530	Tenth terrific Euli survey!
84190	The elegant eleventh Eulachon survey (first in the northern region).
84270	The titanic twelfth Eulachon survey (second in the northern survey area).
84330	The 13th Eulachon survey (third in the northern survey area).
84410	The fourteenth philisophical eulachon survey (fourth in the northern survey area).
84431	Fifteenth flexible Eulachon Survey (fished southern survey area instead of northern due to weather).
84450	Sixteenth Swashbuckling Eulachon Survey (fifth in the northern survey area).
84451	Seventeenth symbolic (and final) Eulachon survey! (sixth in the northern survey area).

**Comment by seananderson** [comment]
Thanks for the issue!

Bonus points if titles like "Eighth Enlightening Eulachon Extravaganza!" are the official `survey_series` names in GFBio.

If not, I suggest an `enthusiastic_survey_series_names` logical argument. :)

**Comment by cgrandin** [comment]
OK, Elise discovered that the grouping codes needed to be added and Norm has added them. Thanks Norm and Elise!

The codes are survey_series_id 80 and 88 for South and North Eulachon surveys
